fix: missing header file
like:
```
error: implicit instantiation of undefined template 'QMap<QLocalSocket *, ConnectionInfo>'
  101 |     QMap<QLocalSocket*, ConnectionInfo> connectionMap;
```